import { Octokit } from '@octokit/rest';
import { PullRequestContext, ReviewComment, RepoConfig, Severity } from '../types';

const SEVERITY_EMOJI: Record<Severity, string> = {
  bug: '🐛',
  security: '🔒',
  suggestion: '💡',
  nitpick: '🔍',
};

export async function postReview(
  octokit: Octokit,
  context: PullRequestContext,
  comments: ReviewComment[],
  _config: Partial<RepoConfig>,
): Promise<void> {
  const { owner, repo, pullNumber, commitSha } = context;

  const summary = buildSummary(comments);

  const reviewComments = comments.map((c) => ({
    path: c.file,
    line: Number(c.line),
    body: formatComment(c),
  }));

  await octokit.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews', {
    owner,
    repo,
    pull_number: pullNumber,
    commit_id: commitSha,
    body: summary,
    event: 'COMMENT' as const,
    comments: reviewComments,
  });
}

function buildSummary(comments: ReviewComment[]): string {
  if (comments.length === 0) {
    return '## 🤖 AI Review Summary\n\nNo issues found. Looks good! ✅';
  }

  const counts = comments.reduce<Partial<Record<Severity, number>>>((acc, c) => {
    acc[c.severity] = (acc[c.severity] ?? 0) + 1;
    return acc;
  }, {});

  const countLines = (Object.entries(counts) as [Severity, number][])
    .map(([sev, n]) => `- ${SEVERITY_EMOJI[sev]} **${sev}**: ${n}`)
    .join('\n');

  return [
    '## 🤖 AI Review Summary',
    '',
    `Found **${comments.length}** issue(s):`,
    countLines,
    '',
    '_Review generated by ReviewBot using Gemini. This is an automated first pass — always apply human judgment._',
  ].join('\n');
}

function formatComment(c: ReviewComment): string {
  const emoji = SEVERITY_EMOJI[c.severity] ?? '';
  return `**${emoji} [${c.severity}]** ${c.comment}`;
}

export async function postFailureComment(
  octokit: Octokit,
  context: PullRequestContext,
  err: Error,
): Promise<void> {
  const { owner, repo, pullNumber } = context;

  let message = '## 🤖 AI Review — Failed\n\nThe automated review could not be completed.';

  if (err.message.includes('diff')) {
    message += '\n\n> Could not fetch PR diff from GitHub.';
  } else if (err.message.includes('LLM') || err.message.toLowerCase().includes('gemini')) {
    message += '\n\n> AI service is currently unavailable. Please try again later.';
  } else {
    message += `\n\n> ${err.message}`;
  }

  await octokit.request('POST /repos/{owner}/{repo}/issues/{issue_number}/comments', {
    owner,
    repo,
    issue_number: pullNumber,
    body: message,
  });
}
